name:                Haskell-AOC-y2023
version:             0.1.0.0
github:              "gagandeepkalra/Haskell-AOC-y2023"
license:             BSD-3-Clause
author:              "gagandeep kalra"
maintainer:          "gagandeepkalra1994@gmail.com"
copyright:           "2023 gagandeep kalra"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gagandeepkalra/Haskell-AOC-y2023#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- parsec
- split

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  Haskell-AOC-y2023-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskell-AOC-y2023

tests:
  Haskell-AOC-y2023-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskell-AOC-y2023
